# Generated by Django 4.1.3 on 2023-06-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('blogtext', models.TextField()),
                ('blogtitle', models.CharField(max_length=255)),
                ('blogtopic', models.CharField(max_length=255)),
                ('blogauthor', models.CharField(max_length=255)),
                ('blogdate', models.DateTimeField()),
                ('bloglikes', models.IntegerField(default=0)),
                ('blogdislikes', models.IntegerField(default=0)),
                ('blogimage', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-blogdate'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_author', models.CharField(max_length=255)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogPost.blog')),
            ],
        ),
    ]
